" Unmap
macmenu &File.New\ Tab                       key=<Nop>
macmenu &File.New\ Window                    key=<Nop>
macmenu &File.Open\.\.\.                     key=<Nop>
macmenu &File.Open\ Tab\.\.\.                key=<Nop>
macmenu &File.Close\ Window                  key=<Nop>
macmenu &File.Close                          key=<Nop>
macmenu &File.Save                           key=<Nop>
macmenu &File.Save\ All                      key=<Nop>
macmenu &File.Save\ As\.\.\.                 key=<Nop>
macmenu &File.Print                          key=<Nop>
macmenu &Edit.Undo                           key=<Nop>
macmenu &Edit.Redo                           key=<Nop>
macmenu &Edit.Cut                            key=<Nop>
macmenu &Edit.Emoji\ &\ Symbols              key=<Nop>
macmenu &Tools.Make                          key=<Nop>
macmenu &Tools.List\ Errors                  key=<Nop>
macmenu &Tools.Next\ Error                   key=<Nop>
macmenu &Tools.Previous\ Error               key=<Nop>
macmenu &Tools.Older\ List                   key=<Nop>
macmenu &Tools.Newer\ List                   key=<Nop>
macmenu &Tools.Spelling.To\ Next\ Error      key=<Nop>
macmenu &Tools.Spelling.Suggest\ Corrections key=<Nop>
macmenu Window.Zoom                          key=<Nop>
macmenu Window.Zoom\ All                     key=<Nop>
macmenu Window.Select\ Next\ Tab             key=<Nop>
macmenu Window.Select\ Previous\ Tab         key=<Nop>
macmenu &Help.MacVim\ Help                   key=<Nop>
